; PlatformIO Project Configuration – Percobaan 04
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    emelianov/modbus-esp8266@^4.1.0
monitor_speed = 115200
upload_speed = 921600
